### ISSUE TITLE
Cannot open Firmen

### ISSUE THREAD

**Issue by Monika1180** [rizonesoft/Resolute#16]
'To start, if you have not done so, install Firemin and open it by double clicking on the tray icon, or right-clicking on the tray icon and choosing Open Firemin.'
Does not work. I never get to the Main Firemin screen. I can see that firemin is open in the task manager. It seems to take a lot of resources and doesn't let me choose the browser or any settings. I am using 86.0.1. What to do? Thank you

**Comment by rizonesoft** [comment]
I apologise for the late reply. I send you an email regarding this issue and will post the solution here as soon as it is resolved.
