### ISSUE TITLE
Firemin for the upper taskbar

### ISSUE THREAD

**Issue by maboroshin** [rizonesoft/Resolute#21]
If I have the taskbar set at the top, I cannot use the Firemin title bar.

Use Alt + space to move. However, when I display it again, the same phenomenon occurs.

Please detect the screen size and title bar position, and add the difference to the window's initial position.

![Clipboard Image](https://user-images.githubusercontent.com/41102508/113482255-b8d8e100-94d8-11eb-8b8f-e934305a71c9.jpg)

**Comment by rizonesoft** [comment]
I apologise for the late reply. I've set the startup position of the main window to the centre of the screen. This should solve your issues.

The new version should be available in a few days.

**Comment by maboroshin** [comment]
The new version solved the issue. Thank you!
