### ISSUE TITLE
Russian text encoding

### ISSUE THREAD

**Issue by Ze2QvoQxxKeu** [rizonesoft/Resolute#3]
Console output in Russian Windows version return text in [OEM 866](https://en.wikipedia.org/wiki/Code_page_866) encoding, need convert it before showing.

![Безымянный](https://user-images.githubusercontent.com/17485135/109376350-4a06d780-78dd-11eb-914d-76b8a572e79c.png)
**Log:** [ComIntRep.log](https://github.com/rizonesoft/Resolute/files/6053773/ComIntRep.log)
# 
Also a good update the language strings for translation - not the entire interface is translated.
For example, `File -> Preferences -> Perfomance -> Priority` (Low, High, etc...), and some others.

**Updated Russian language file:** [Russian20210227.zip](https://github.com/rizonesoft/Resolute/files/6053802/Russian20210227.zip)

**Comment by rizonesoft** [comment]
Thank you for the translation. I will work on an update per your recommendation. Should be ready with an update in a few days.
